# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/oem/xauiexmaple/xauiexmaple.srcs/sources_1/ip/xaui_0/xaui_0.xci
# IP: The module: 'xaui_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/oem/xauiexmaple/xauiexmaple.srcs/sources_1/ip/xaui_0/synth/xaui_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'xaui_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/oem/xauiexmaple/xauiexmaple.srcs/sources_1/ip/xaui_0/synth/xaui_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xaui_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/oem/xauiexmaple/xauiexmaple.srcs/sources_1/ip/xaui_0/xaui_0.xci
# IP: The module: 'xaui_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/oem/xauiexmaple/xauiexmaple.srcs/sources_1/ip/xaui_0/synth/xaui_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'xaui_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/oem/xauiexmaple/xauiexmaple.srcs/sources_1/ip/xaui_0/synth/xaui_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xaui_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
